name: Check Version Number

on:
  pull_request:
    branches:
      - main

jobs:
  check_version:
    name: Check Version Number
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: dudo/tag_check@v1.0.0
        with:
          git_tag_prefix: v
