name: Push (main)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  get_package_version:
    name: Get Package Version
    runs-on: ubuntu-latest
    outputs:
      git_tag_name: ${{ steps.tag_check.outputs.git_tag_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: dudo/tag_check@v1.0.0
        id: tag_check
        with:
          git_tag_prefix: v
  add_git_tag:
    name: Add GitHub Release
    needs: get_package_version
    runs-on: ubuntu-latest
    steps:
      - name: Push Release
        run: |
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
          -d "{\"tag_name\": \"v${{needs.get_package_version.outputs.git_tag_name}}\", \"target_commitish\": \"${GITHUB_SHA}\", \"name\": \"v${{needs.get_package_version.outputs.git_tag_name}}\", \"body\": \"Release v${{needs.get_package_version.outputs.git_tag_name}}\", \"draft\": false, \"prerelease\": false }" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs"
