---

name: Push (main)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

on:
  push:
    branches:
    - main

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: |
        chmod +x .github/scripts/create-github-release.sh
        .github/scripts/create-github-release.sh

  create_npm_release:
    name: Create NPM Release
    runs-on: ubuntu-latest
    needs: create_github_release
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
        npm install --global yarn
        yarn bootstrap:ci
        yarn build
        yarn ship
