name: Create Pull Request

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - main

jobs:
  check_package_version:
    name: Check Package Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: dudo/tag_check@v1.0.0
        with:
          git_tag_prefix: v
