name: Merge (main)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  get_package_version:
    name: Get Package Version
    runs-on: ubuntu-latest
    outputs:
      git_tag_name: ${{ steps.tag_check.outputs.git_tag_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: dudo/tag_check@v1.0.0
        id: tag_check
        with:
          git_tag_prefix: v
  create_github_release:
    name: Create GitHub Release
    needs: get_package_version
    runs-on: ubuntu-latest
    steps:
      - run: |
          chmod +x ../scripts/*
          ../scripts/create-github-release.sh
        shell: bash
