name: Merge Pull Request

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  get_package_version:
    name: Get Package Version
    runs-on: ubuntu-latest
    outputs:
      git_tag_name: ${{ steps.tag_check.outputs.git_tag_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: dudo/tag_check@v1.0.0
        id: tag_check
        with:
          git_tag_prefix: v
  create_github_release:
    name: Create GitHub Release
    needs: get_package_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: .github/scripts/create-github-release.sh
