name: Pull Request (main)

on:
  pull_request:
    branches:
      - main

jobs:
  check_package_version:
    name: Check Package Version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: ../scripts/testing.sh
        with:
          git_tag_prefix: v
